import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-slate-900">
      <body className={sora.className}>
        <main className="min-h-screen px-8 max-w-7xl mx-auto py-20">
          {children}
          <div className="background-gradient absolute inset-0 -z-50 max-h-screen" />
          <div className="pointer-events-none fixed inset-0 -z-40 h-screen w-full bg-[url('/noisetexture.jpg')] opacity-20 mix-blend-soft-light"></div>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
